[default]
address = "0.0.0.0"
port = 1027
log_level = "normal"

[debug]
address = "0.0.0.0"
port = 1028
log_level = "debug"

[release]
address = "0.0.0.0"
port = 1027
log_level = "critical"
secret_key = "2yY6o0fkK9rA9NBe+vzMR71xc7FJUrjyHTIwqoGzAwN/lYw/U1FE7/zBWG4N3xZwsv2kpnTL9uUG067QW83BGg=="
